Fixing validation errors against v1.18
=== ERROR: Job/spec.activeDeadlineSeconds/timeout.yaml
The Job "jobs-timeout-job" is invalid: spec.template.spec.restartPolicy: Unsupported value: "Always": supported values: "OnFailure", "Never"

=== ERROR: Pod/spec.containers.securityContext/privileged-namespace.yaml
error: error validating "Pod/spec.containers.securityContext/privileged-namespace.yaml": error validating data: ValidationError(Pod.spec): unknown field "hostUTS" in io.k8s.api.core.v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false

=== ERROR: Pod/spec.containers.volumes.projected/projected.yaml
error: error validating "Pod/spec.containers.volumes.projected/projected.yaml": error validating data: ValidationError(Pod.spec.volumes[0].projected.sources[0].secret): unknown field "mode" in io.k8s.api.core.v1.SecretProjection; if you choose to ignore these errors, turn validation off with --validate=false

=== ERROR: Pod/spec.topologySpreadConstraints/topology-spread-constraints-with-node-affinity.yaml
from server for: "Pod/spec.topologySpreadConstraints/topology-spread-constraints-with-node-affinity.yaml": invalid resource name "topology-spread-constraints/topology-spread-constraints-with-node-affinity-pod": [may not contain '/']

=== ERROR: Pod/spec.volumes.hostPath.type/file-or-create.yaml
The Pod "volumes-file-or-create-pod" is invalid: spec.containers[0].image: Required value

=== ERROR: Pod/taints_and_tolerations/toleration.yaml
for: "Pod/taints_and_tolerations/toleration.yaml": pods "pod-toleration" not found

=== ERROR: PodSecurityPolicy/Ingress/simple.yaml
error: unable to recognize "PodSecurityPolicy/Ingress/simple.yaml": no matches for kind "Ingress" in version "networking.k8s.io/v1"

=== ERROR: Service/spec.type/load-balancer.yaml
The Service "service-load-balancer-service" is invalid: spec.clusterIP: Invalid value: "10.0.171.239": provided IP is not in the valid range. The range of valid IPs is 10.43.0.0/16